# -*- coding: utf-8 -*-
"""atividade-gs.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lozX5OopW4RyvhK0wWg3A4hCZkQ1hvVB
"""

# ==============================================================================
# FIAP - Data Science: Artificial Intelligence, Analytics, Cloud & Data Platforms
# Disciplina: Data Driven Application & Data Science
# Avaliação: 2026 1ª Global Solutions
# ==============================================================================
# INTEGRANTES:
# 1. [Nome do Aluno 1] - RM: [XXXXX] (Representante)
# 2. [Nome do Aluno 2] - RM: [XXXXX]
# 3. [Nome do Aluno 3] - RM: [XXXXX]
# ==============================================================================

# 2. Inicialização das Listas de Armazenamento
# Cria listas vazias para guardar as informações de cada evento separadamente.
tipos_eventos = []
paises = []
regioes = []
cidades = []
areas_afetadas = []
intensidades = []
ocorrencias = []

print("======================================================================")
print("     SISTEMA DE MONITORAMENTO ESPACIAL AMBIENTAL - BRASIL      ")
print("======================================================================")